---
# tasks file for roles/common
- name: Update APT cache
  apt:
    update_cache: yes

- name: Install Apache
  apt:
    name: apache2
    state: present

- name: Install MariaDB
  apt:
    name: mariadb-server
    state: present

- name: Install PHP and extensions
  apt:
    name: "{{ php_packages }}"
    state: present

- name: Start and enable Apache
  service:
    name: apache2
    state: started
    enabled: yes

- name: Start and enable MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Deploy info.php test page
  copy:
    dest: /var/www/html/info.php
    content: "<?php phpinfo(); ?>"
    mode: '0644'
